import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("activity", "routes/activity.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("welcome", "routes/welcome.tsx"),
  route("import", "routes/import.tsx"),
  route("api/auth/*", "routes/api.auth.tsx"),
  route("films/search", "routes/films.search.tsx"),
  route("film/:tmdbId", "routes/film.tsx"),
  route("film/:tmdbId/log", "routes/film.log.tsx"),
  route("entries/:entryId", "routes/entry.tsx"),
  route("u/:username", "routes/profile.tsx"),
  route("u/:username/films", "routes/profile.films.tsx"),
  route("u/:username/diary", "routes/profile.diary.tsx"),
  route("u/:username/reviews", "routes/profile.reviews.tsx"),
  route("u/:username/lists", "routes/profile.lists.tsx"),
  route("u/:username/watchlist", "routes/profile.watchlist.tsx"),
  route("u/:username/likes", "routes/profile.likes.tsx"),
  route("u/:username/followers", "routes/profile.followers.tsx"),
  route("u/:username/following", "routes/profile.following.tsx"),
  route("lists/new", "routes/lists.new.tsx"),
  route("lists/:listId", "routes/list.tsx"),
  route("lists/:listId/edit", "routes/list.edit.tsx"),
  route("settings/data", "routes/settings.data.tsx"),
  route("settings/profile", "routes/settings.profile.tsx"),
  route("export/json", "routes/export.json.tsx"),
  route("export/csv", "routes/export.csv.tsx"),
] satisfies RouteConfig;
